"""Strict, dependency-free Markdown front-matter handling."""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re
import subprocess

REQUIRED = ("Evidence", "Revision", "Status", "Applicability", "Confidence")
OPTIONAL_LISTS = ("Audience", "Topics", "Symbols")
# Metadata written by older Codex-integrated releases is accepted on read and
# normalized to the stable Core role vocabulary.
LEGACY_AUDIENCE = {
    "luna": "investigator",
    "luna-investigator": "investigator",
    "luna-curator": "curator",
    "sol-high": "reasoning-specialist",
    "terra-implementer": "implementer",
    "terra-reviewer": "reviewer",
}


@dataclass(frozen=True)
class Entry:
    path: Path
    meta: dict[str, object]
    body: str


def parse(path: Path) -> Entry:
    return parse_text(path.read_text(encoding="utf-8"), path)


def parse_text(text: str, path: Path | None = None) -> Entry:
    """Parse exact generated bytes in memory or a persisted Markdown file."""
    source = path or Path("<memory>")
    if not text.startswith("---\n"):
        raise ValueError(f"{source}: missing front matter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError(f"{source}: unterminated front matter")
    meta: dict[str, object] = {}
    for line in text[4:end].splitlines():
        match = re.fullmatch(r"([A-Za-z][A-Za-z ]*): (.+)", line)
        if not match:
            raise ValueError(f"{source}: invalid front matter line")
        key, raw = match.groups()
        if key in meta:
            raise ValueError(f"{source}: duplicate front matter field {key}")
        try:
            meta[key] = json.loads(raw) if raw.startswith("[") else raw
        except json.JSONDecodeError as exc:
            raise ValueError(f"{source}: invalid list field {key}") from exc
    missing = set(REQUIRED) - set(meta)
    if missing:
        raise ValueError(f"{source}: required metadata invalid")
    if not isinstance(meta["Revision"], str) or not re.fullmatch(r"[1-9][0-9]*", meta["Revision"]):
        raise ValueError(f"{source}: Revision must be a positive integer")
    for key in OPTIONAL_LISTS:
        if key in meta and (not isinstance(meta[key], list) or not all(isinstance(item, str) and item for item in meta[key])):
            raise ValueError(f"{source}: {key} must be a JSON string list")
    # Status, confidence, applicability, kind, and audience are model-authored
    # display/search metadata. Parsing them never grants routing authority.
    for key in ("Status", "Confidence", "Applicability", "Kind"):
        if key in meta and (not isinstance(meta[key], str) or not meta[key] or len(meta[key]) > 128):
            raise ValueError(f"{source}: {key} must be bounded text")
    return Entry(source, meta, text[end + 5:])


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def evidence_status(entry: Entry, root: Path) -> tuple[str, list[str]]:
    """Evaluate file/content evidence without changing the recorded fact."""
    evidence = entry.meta["Evidence"]
    specs = evidence if isinstance(evidence, list) else ([] if evidence == "NONE" else [evidence])
    if not specs:
        return "UNKNOWN", []
    missing: list[str] = []
    changed: list[str] = []
    invalid: list[str] = []
    for spec in specs:
        if not isinstance(spec, str):
            invalid.append("invalid evidence")
            continue
        # file:relative/path#content-sha256 and git:relative/path#blob-sha1
        match = re.fullmatch(r"(?:file|git):([^#]+)#([0-9a-fA-F]{40,64})", spec)
        if not match:
            invalid.append(spec)
            continue
        candidate = (root / match.group(1)).resolve()
        try:
            candidate.relative_to(root.resolve())
        except ValueError:
            invalid.append(match.group(1))
            continue
        if not candidate.is_file():
            missing.append(match.group(1))
            continue
        kind = spec.split(":", 1)[0]
        if kind == "git":
            relative = str(candidate.relative_to(root)).replace("\\", "/")
            tracked = subprocess.run(["git", "ls-files", "--error-unmatch", "--", relative], cwd=root, capture_output=True, text=True, check=False)
            indexed = subprocess.run(["git", "rev-parse", "--verify", f":{relative}"], cwd=root, capture_output=True, text=True, check=False)
            probe = subprocess.run(["git", "hash-object", "--", relative], cwd=root, capture_output=True, text=True, check=False)
            actual = probe.stdout.strip() if tracked.returncode == indexed.returncode == probe.returncode == 0 and indexed.stdout.strip().lower() == match.group(2).lower() else ""
        else:
            actual = sha256(candidate)
        if actual.lower() != match.group(2).lower():
            changed.append(match.group(1))
    if missing:
        return "MISSING", missing
    if changed:
        return "CHANGED", changed
    if invalid:
        return "UNKNOWN", invalid
    return "FRESH", []
