"""Strict, dependency-free Markdown front-matter handling."""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re
import subprocess

REQUIRED = ("Evidence", "Revision", "Status", "Applicability", "Confidence")
OPTIONAL_LISTS = ("Audience", "Topics", "Symbols")
# Freshness detail is diagnostic, while durable bodies and provenance are the
# retrieval contract.  Keep diagnostics bounded so later source churn cannot
# inflate a previously readable document-get response.
FRESHNESS_DETAIL_MAX_BYTES = 2048


@dataclass(frozen=True)
class Entry:
    path: Path
    meta: dict[str, object]
    body: str


def parse(path: Path) -> Entry:
    return parse_text(path.read_text(encoding="utf-8"), path)


def parse_text(text: str, path: Path | None = None) -> Entry:
    """Parse exact generated bytes in memory or a persisted Markdown file."""
    source = path or Path("<memory>")
    if not text.startswith("---\n"):
        raise ValueError(f"{source}: missing front matter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError(f"{source}: unterminated front matter")
    meta: dict[str, object] = {}
    for line in text[4:end].splitlines():
        match = re.fullmatch(r"([A-Za-z][A-Za-z ]*): (.+)", line)
        if not match:
            raise ValueError(f"{source}: invalid front matter line")
        key, raw = match.groups()
        if key in meta:
            raise ValueError(f"{source}: duplicate front matter field {key}")
        try:
            meta[key] = json.loads(raw) if raw.startswith("[") else raw
        except json.JSONDecodeError as exc:
            raise ValueError(f"{source}: invalid list field {key}") from exc
    missing = set(REQUIRED) - set(meta)
    if missing:
        raise ValueError(f"{source}: required metadata invalid")
    if not isinstance(meta["Revision"], str) or not re.fullmatch(r"[1-9][0-9]*", meta["Revision"]):
        raise ValueError(f"{source}: Revision must be a positive integer")
    for key in OPTIONAL_LISTS:
        if key in meta and (not isinstance(meta[key], list) or not all(isinstance(item, str) and item for item in meta[key])):
            raise ValueError(f"{source}: {key} must be a JSON string list")
    # Status, confidence, applicability, kind, and audience are model-authored
    # display/search metadata. Parsing them never grants routing authority.
    for key in ("Status", "Confidence", "Applicability", "Kind"):
        if key in meta and (not isinstance(meta[key], str) or not meta[key] or len(meta[key]) > 128):
            raise ValueError(f"{source}: {key} must be bounded text")
    return Entry(source, meta, text[end + 5:])


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def evidence_status(entry: Entry, root: Path) -> tuple[str, list[str]]:
    """Evaluate file/content evidence without changing the recorded fact."""
    evidence = entry.meta["Evidence"]
    if evidence == "DURABLE_SOURCE_DESCRIPTORS":
        status, detail = _durable_descriptor_status(entry, root)
        return status, _bounded_freshness_detail(detail)
    specs = evidence if isinstance(evidence, list) else ([] if evidence == "NONE" else [evidence])
    if not specs:
        return "UNKNOWN", []
    missing: list[str] = []
    changed: list[str] = []
    invalid: list[str] = []
    for spec in specs:
        if not isinstance(spec, str):
            invalid.append("invalid evidence")
            continue
        # file:relative/path#content-sha256 and git:relative/path#blob-sha1
        match = re.fullmatch(r"(?:file|git):([^#]+)#([0-9a-fA-F]{40,64})", spec)
        if not match:
            invalid.append(spec)
            continue
        lexical = root / match.group(1)
        if lexical.is_symlink():
            missing.append(match.group(1))
            continue
        candidate = lexical.resolve()
        try:
            candidate.relative_to(root.resolve())
        except ValueError:
            invalid.append(match.group(1))
            continue
        if not candidate.is_file():
            missing.append(match.group(1))
            continue
        kind = spec.split(":", 1)[0]
        if kind == "git":
            relative = str(candidate.relative_to(root)).replace("\\", "/")
            tracked = subprocess.run(["git", "ls-files", "--error-unmatch", "--", relative], cwd=root, capture_output=True, text=True, check=False)
            indexed = subprocess.run(["git", "rev-parse", "--verify", f":{relative}"], cwd=root, capture_output=True, text=True, check=False)
            probe = subprocess.run(["git", "hash-object", "--", relative], cwd=root, capture_output=True, text=True, check=False)
            actual = probe.stdout.strip() if tracked.returncode == indexed.returncode == probe.returncode == 0 and indexed.stdout.strip().lower() == match.group(2).lower() else ""
        else:
            actual = sha256(candidate)
        if actual.lower() != match.group(2).lower():
            changed.append(match.group(1))
    if missing:
        return "MISSING", _bounded_freshness_detail(missing)
    if changed:
        return "CHANGED", _bounded_freshness_detail(changed)
    if invalid:
        return "UNKNOWN", _bounded_freshness_detail(invalid)
    return "FRESH", []


def _bounded_freshness_detail(detail: list[str]) -> list[str]:
    """Return a deterministic JSON-byte-bounded diagnostic list.

    The budget is measured in the same UTF-8 JSON representation as public
    responses.  Sorting removes descriptor/source ordering as an output-size
    influence; the marker itself is admitted only when it fits the budget.
    """
    ordered = sorted(str(item) for item in detail)
    accepted: list[str] = []
    for item in ordered:
        if len(json.dumps(accepted + [item], ensure_ascii=False, separators=(",", ":")).encode("utf-8")) > FRESHNESS_DETAIL_MAX_BYTES:
            break
        accepted.append(item)
    omitted = len(ordered) - len(accepted)
    if omitted:
        marker = f"... {omitted} additional freshness detail entries omitted"
        while accepted and len(json.dumps(accepted + [marker], ensure_ascii=False, separators=(",", ":")).encode("utf-8")) > FRESHNESS_DETAIL_MAX_BYTES:
            accepted.pop()
            omitted += 1
            marker = f"... {omitted} additional freshness detail entries omitted"
        if len(json.dumps(accepted + [marker], ensure_ascii=False, separators=(",", ":")).encode("utf-8")) <= FRESHNESS_DETAIL_MAX_BYTES:
            accepted.append(marker)
    return accepted


def freshness_detail_budget_placeholder() -> list[str]:
    """Largest ASCII detail list admitted by the public diagnostic budget."""
    return ["x" * (FRESHNESS_DETAIL_MAX_BYTES - 4)]


def _durable_descriptor_status(entry: Entry, root: Path) -> tuple[str, list[str]]:
    """Check only durable descriptors that carry an objective path/hash pair."""
    descriptors = durable_descriptors(entry)
    if descriptors is None:
        return "UNKNOWN", ["invalid durable source descriptors"]

    specs: list[str] = []
    missing: list[str] = []
    changed: list[str] = []
    invalid: list[str] = []
    checked = False
    recorded = 0
    for descriptor in descriptors:
        if descriptor.get("type") == "artifact":
            path = descriptor.get("path")
            identity = descriptor.get("content_sha256")
            if not isinstance(path, str) or not isinstance(identity, str) or not re.fullmatch(r"[0-9a-fA-F]{64}", identity):
                invalid.append(str(descriptor.get("artifact_id", "invalid artifact descriptor")))
                continue
            checked = True
            lexical = root / path
            if lexical.is_symlink():
                missing.append(path)
                continue
            candidate = lexical.resolve()
            try:
                candidate.relative_to(root.resolve())
            except ValueError:
                invalid.append(path)
                continue
            if not candidate.is_file():
                missing.append(path)
            elif sha256(candidate).lower() != identity.lower():
                changed.append(path)
        elif descriptor.get("type") == "source":
            locator = descriptor.get("locator")
            if isinstance(locator, str) and re.fullmatch(r"(?:file|git):[^#]+#[0-9a-fA-F]{40,64}", locator):
                specs.append(locator)
            else:
                recorded += 1
        else:
            invalid.append("invalid durable descriptor type")
    if specs:
        checked = True
        mechanical = Entry(entry.path, {**entry.meta, "Evidence": specs}, entry.body)
        status, detail = evidence_status(mechanical, root)
        if status == "MISSING":
            missing.extend(detail)
        elif status == "CHANGED":
            changed.extend(detail)
        elif status == "UNKNOWN":
            invalid.extend(detail)
    if missing:
        return "MISSING", missing
    if changed:
        return "CHANGED", changed
    if invalid:
        return "UNKNOWN", invalid
    if not checked:
        return "RECORDED", []
    if recorded:
        return "PARTIAL", []
    return "FRESH", []


def durable_descriptors(entry: Entry) -> list[dict[str, object]] | None:
    """Return persisted mechanical provenance descriptors without interpreting them."""
    marker = "## Durable Source Descriptors\n\n```json\n"
    start = entry.body.rfind(marker)
    match = re.fullmatch(r"(\[.*\])\n```\s*", entry.body[start + len(marker):], re.DOTALL) if start >= 0 else None
    if match is None:
        return None
    try:
        descriptors = json.loads(match.group(1))
    except json.JSONDecodeError:
        return None
    if not isinstance(descriptors, list) or not all(isinstance(item, dict) for item in descriptors):
        return None
    return descriptors
